export const NASA = {
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAIL: 'SEARCH_FAIL'
};

export const COLLECTION = {
  FETCH_LOCAL_REQUEST: 'FETCH_LOCAL_REQUEST',
  FETCH_LOCAL_SUCCESS: 'FETCH_LOCAL_SUCCESS',
  FETCH_LOCAL_FAIL: 'FETCH_LOCAL_FAIL'
};
