export const NASA = {
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAIL: 'SEARCH_FAIL'
};

export const COLLECTION = {
  FETCH_LOCAL_REQUEST: 'FETCH_LOCAL_REQUEST',
  FETCH_LOCAL_SUCCESS: 'FETCH_LOCAL_SUCCESS',
  FETCH_LOCAL_FAIL: 'FETCH_LOCAL_FAIL',

  ADD_NASA_REQUEST: 'ADD_NASA_REQUEST',
  ADD_NASA_SUCCESS: 'ADD_NASA_SUCCESS',
  ADD_NASA_FAIL: 'ADD_NASA_FAIL',

  REMOVE_NASA_REQUEST: 'REMOVE_NASA_REQUEST',
  REMOVE_NASA_SUCCESS: 'REMOVE_NASA_SUCCESS',
  REMOVE_NASA_FAIL: 'REMOVE_NASA_FAIL',

  UPDATE_NASA_REQUEST: 'UPDATE_NASA_REQUEST',
  UPDATE_NASA_SUCCESS: 'UPDATE_NASA_SUCCESS',
  UPDATE_NASA_FAIL: 'UPDATE_NASA_FAIL'
};
